log:
  root_dir: "artifacts/log"
  version: null
  to_file: false
  log_every_n_steps: 5 # expensive computation
  flush_logs_every_n_steps: 10 # expensive computation

chkpt:
  root_dir: "artifacts/checkpoints"
  monitor: "val_loss" # metric to determine if to save
  save_top_k: 1 # only top k models to be save
  every_n_val_epochs: null # save after n (training) epochs. It works if save_top_k > 0
  every_n_train_steps: null # mutually exclusive to every_n_val_epochs
  save_last: true # only work after the first validation step

arcface:
  pth: "artifacts/experiments/idt_encoder/ArcFace.pth"
  vector_size: 256

data:
  trainset_dir: "artifacts/datasets/ffhq/train"
  valset_dir: "artifacts/datasets/ffhq/val"

trainer:
  batch_size: 2 # 32 should work

  num_workers: 0
  max_epoch: 1000
  num_processes: 1 # for distributed computation
  
  val_check_interval: 1.0

  limit_train_batches: 1.0 # TODO: review the option
  limit_val_batches: 1.0 # TODO: review the option

  gpus: 0
  num_sanity_val_steps: 0

  accumulate_grad_batches: 8

model:
  name: "faceshifter"
  experiment: "other_research_code" # to create log and checkpoint dir

  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  grad_clip: 0.0