log:
  log_dir: 'artifacts/log'
  chkpt_dir: 'artifacts/checkpoints'


arcface:
  chkpt_path: 'artifacts/experiments/idt_encoder/ArcFace.pth'
  vector_size: 256

data:
  dataset_dir: 'artifacts/datasets/ffhq_sample'
  valset_dir: 'artifacts/datasets/ffhq_sample'

model:
  learning_rate_E_G: 4e-4
  learning_rate_D: 4e-4

  beta1: 0
  beta2: 0.999

  batch_size: 2

  num_workers: 1
  grad_clip: 0.0